.TH PATCHMATRIX_MONITOR "1" "Apr 13, 2020"

.SH NAME
patchmatrix_monitor \- a JACK port monitor

.SH SYNOPSIS
.B patchmatrix_monitor
[\fIoptions\fR]

.SH DESCRIPTION
\fBpatchmatrix_monitor\fP is a JACK port monitor.
.PP
To be used in conjunction with \fBpatchmatrix\fP.
.PP
Ships with JACK session management support.

.SH OPTIONS
.HP
\fB\-v\fR
.IP
Print version and license information

.HP
\fB\-h\fR
.IP
Print usage information

.HP
\fB\-t\fR port-type
.IP
Port type (audio, midi)

.HP
\fB\-i\fR input-num
.IP
Number of input ports (1-128)

.HP
\fB\-n\fR server-name
.IP
Connect to named JACK daemon

.HP
\fB\-u\fR client-uuid
.IP
Client UUID for JACK session management

.HP
\fB\-d\fR session-dir
.IP
Directory for JACK session management

.SH LICENSE
Artistic License 2.0.

.SH AUTHOR
Hanspeter Portner (dev@open-music-kontrollers.ch).

.SH SEE ALSO
jackd(1), patchmatrix(1), patchmatrix_mixer(1)
