.TH PATCHMATRIX "1" "April 27, 2017"

.SH NAME
patchmatrix \- a JACK patchbay

.SH SYNOPSIS
.B patchmatrix
[\fIoptions\fR]

.SH DESCRIPTION
\fBpatchmatrix\fP is a JACK patchbay.
.PP
It shows JACK clients and their input and output ports in flow-matrix-style.
.PP
The flow-matrix-style combines advantages of both flow-style (excellent overview
of signal flow) and matrix-style (less virtual cabling mess, one-click patching).
.PP
The patchbay shows AUDIO, MIDI, CV and OSC ports separately to reduce complexity.

.SH OPTIONS
.HP
\fB\-v\fR
.IP
Print version and license information

.HP
\fB\-h\fR
.IP
Print usage information

.HP
\fB\-n\fR server-name
.IP
Connect to named JACK daemon

.HP
\fB\-u\fR client-uuid
.IP
Client UUID for JACK session management

.HP
\fB\-d\fR session-dir
.IP
Directory for JACK session management

.SH LICENSE
Artistic License 2.0.

.SH AUTHOR
Hanspeter Portner (dev@open-music-kontrollers.ch).

.SH SEE ALSO
jackd(1), patchmatrix_monitor(1), patchmatrix_mixer(1)
