.TH PATCHMATRIX_MIXER "1" "April 27, 2017"

.SH NAME
patchmatrix_mixer \- a JACK port mixer

.SH SYNOPSIS
.B patchmatrix_mixer
[\fIoptions\fR]

.SH DESCRIPTION
\fBpatchmatrix_mixer\fP is a JACK port mixer.
.PP
To be used in conjunction with \fBpatchmatrix\fP.

.SH OPTIONS
.HP
\fB\-v\fR
.IP
Print version and license information

.HP
\fB\-h\fR
.IP
Print usage information

.HP
\fB\-n\fR server-name
.IP
Connect to named JACK daemon

.HP
\fB\-u\fR client-uuid
.IP
Client UUID for JACK session management

.HP
\fB\-t\fR port-type
.IP
Port type (audio, midi)

.HP
\fB\-i\fR input-num
.IP
Number of input ports (1-16)

.HP
\fB\-o\fR output-num
.IP
Number of output ports (1-16)

.SH LICENSE
Artistic License 2.0.

.SH AUTHOR
Hanspeter Portner (dev@open-music-kontrollers.ch).

.SH SEE ALSO
jackd(1), patchmatrix(1), patchmatrix_monitor(1)
