# SPDX-FileCopyrightText: Hanspeter Portner <dev@open-music-kontrollers.ch>
# SPDX-License-Identifier: CC0-1.0

---

image: alpine/latest

packages:
  - clang16-analyzer
  - llvm16
  - reuse
  - meson
  - hut
  - jq
  - valgrind
  - lv2-dev
  - glu-dev
  - glew-dev
  - libx11-dev
  - libxext-dev
  - jack-dev

environment:
  project: patchmatrix

secrets:
  - 0545580c-42ac-4700-b322-4e9df924eb07 # runner-ssh
  - 5fe806cd-3af4-4588-9898-8115d9262144 # hut-config
  - d6d10b2a-542a-4b45-b1be-6ef30a8ab558 # git-config
  - 3de1773e-3503-46f5-8ab4-5212026517f4 # pgp-key

sources:
  - https://git.open-music-kontrollers.ch/~hp/ci

tasks:
  - gcc: |
      . ~/ci/activate

      ci-meson gcc setup
      ci-meson gcc build
      ci-meson gcc test
      ci-meson gcc memcheck

  - clang: |
      . ~/ci/activate

      ci-meson clang setup
      ci-meson clang build
      ci-meson clang test
      ci-meson clang memcheck

      #  - analyzer: |
      #      . ~/ci/activate
      #
      #      ci-meson analyzer setup
      #      ci-meson analyzer build
      #      ci-meson analyzer test

  - sign: |
      . ~/ci/activate

      if ! ci-istag; then
        complete-build
      fi

      ci-archivesign


triggers:
  - action: email
    condition: failure
    to: "<dev@open-music-kontrollers.ch>"

...
